package net.kem.newtquickfix.builders;

import org.apache.commons.lang3.StringUtils;

/**
 * Created with IntelliJ IDEA.
 * User: EvgenyK
 * Date: 10/30/14
 * Time: 2:43 PM
 * Generates QF Component interface file.
 */
public class QFMessageInterface {
    private static final String TEMPLATE = "package $PACKAGE_NAME_MESSAGES;\n" +
            "\n" +
            "import $PACKAGE_NAME_COMPONENTS.$CCN;\n" +
            "\n" +
            "/**\n" +
            " * Autogenerated interface for component $CCN.\n" +
            " */\n" +
            "public interface I$CCN {\n" +
            "\t$CCN get$CCN();\n" +
            "\tvoid set$CCN($CCN " + StringUtils.uncapitalize("$CCN") + ");\n" +
            "}";

    public static String buildInterfaceSource(CharSequence componentName) {
        return TEMPLATE
                .replace("$CCN", componentName)
                .replace("$PACKAGE_NAME_MESSAGES", BuilderUtils.PACKAGE_NAME_MESSAGES)
                .replace("$PACKAGE_NAME_COMPONENTS", BuilderUtils.PACKAGE_NAME_COMPONENTS);
    }
}